/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computer.laboratory.inventory.system.frames;

import computer.laboratory.inventory.system.Helper;
import computer.laboratory.inventory.system.Tables;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author Tuason
 */
public class Homepage extends javax.swing.JFrame {

    public Homepage(String room) {
        initComponents();
        
        // INITIALIZE TABLE
        Tables.getInstance().setInventoryTable(inventoryTable);
        
        // UIs
        inventoryTable.getTableHeader().setFont(new Font("Leelawadee UI", Font.BOLD, 12));
        inventoryTable.getTableHeader().setOpaque(false);
        inventoryTable.getTableHeader().setBackground(new Color(255,204,102));
        inventoryTable.getTableHeader().setPreferredSize(new Dimension(header.getWidth(), 25));
        
        inventoryTable.setDefaultRenderer(Object.class, new InventoryItem.AlternateRowColorRenderer());
        
        laboratoryNumberComboBox.setSelectedItem(room);
        
        // DISPLAY UI
        Helper.displayInventory(room);
        
        // KEYPRESS
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterKeyPressed(evt);
            }
        });
    }

    // Custom cell renderer for alternate row colors
    static class AlternateRowColorRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component rendererComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Set alternate row colors
            if (row % 2 == 0) {
                rendererComponent.setBackground(Color.WHITE); // Set the background color for even rows
            } else {
                rendererComponent.setBackground(new Color(240, 240, 240)); // Set the background color for odd rows
            }

            return rendererComponent;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        headerBackground = new javax.swing.JLabel();
        bodyScrollPane = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        addInventoryBtn = new javax.swing.JButton();
        laboratoryNumberComboBox = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setText("COMPUTER LABORATORY INVENTORY SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(255, 204, 102));
        logoutBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.setToolTipText("");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 110, 40));

        header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 70));

        headerBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer/laboratory/inventory/system/images/login-bg.jpg"))); // NOI18N
        header.add(headerBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        container.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        bodyScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Date", "Inventory By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventoryTable.setFocusable(false);
        inventoryTable.setGridColor(new java.awt.Color(0, 0, 0));
        inventoryTable.setRowHeight(25);
        inventoryTable.setSelectionBackground(new java.awt.Color(255, 204, 102));
        inventoryTable.setShowHorizontalLines(true);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventoryTable);
        if (inventoryTable.getColumnModel().getColumnCount() > 0) {
            inventoryTable.getColumnModel().getColumn(0).setMinWidth(100);
            inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            inventoryTable.getColumnModel().getColumn(0).setMaxWidth(100);
            inventoryTable.getColumnModel().getColumn(1).setMinWidth(150);
            inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            inventoryTable.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 880, 350));

        searchField.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        searchField.setToolTipText("Search Inventory");
        searchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        body.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 220, 40));

        addInventoryBtn.setBackground(new java.awt.Color(255, 204, 102));
        addInventoryBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        addInventoryBtn.setText("Add Inventory");
        addInventoryBtn.setToolTipText("Add New Inventory");
        addInventoryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        addInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInventoryBtnActionPerformed(evt);
            }
        });
        body.add(addInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, 40));

        laboratoryNumberComboBox.setBackground(new java.awt.Color(255, 204, 102));
        laboratoryNumberComboBox.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        laboratoryNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laboratory 1", "Laboratory 2" }));
        laboratoryNumberComboBox.setToolTipText("Select Laboratory Room");
        laboratoryNumberComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        laboratoryNumberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratoryNumberComboBoxActionPerformed(evt);
            }
        });
        body.add(laboratoryNumberComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 40));

        searchBtn.setBackground(new java.awt.Color(255, 204, 102));
        searchBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("Search");
        searchBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        body.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 80, 40));

        bodyScrollPane.setViewportView(body);

        container.add(bodyScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void laboratoryNumberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratoryNumberComboBoxActionPerformed
        Helper.displayInventory(laboratoryNumberComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_laboratoryNumberComboBoxActionPerformed

    private void addInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInventoryBtnActionPerformed
        new AddInventory().setVisible(true);
    }//GEN-LAST:event_addInventoryBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchText = searchField.getText();
        Helper.searchInventory(searchText, laboratoryNumberComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_searchBtnActionPerformed

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked
        
        int index = inventoryTable.getSelectedRow();
        TableModel model = inventoryTable.getModel();
        int inventoryId = Integer.parseInt((String) model.getValueAt(index, 0));
        String date = (String) model.getValueAt(index, 1);
        String inventoryBy = (String) model.getValueAt(index, 2);
        String room = laboratoryNumberComboBox.getSelectedItem().toString();
        
        new InventoryItem(room, inventoryId, date, inventoryBy).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryTableMouseClicked

    
    
    // CUSTOM METHODS
    private void enterKeyPressed(java.awt.event.KeyEvent evt) {                                         
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            // Simulate a button click when Enter is pressed
            searchBtn.doClick();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInventoryBtn;
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane bodyScrollPane;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerBackground;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> laboratoryNumberComboBox;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
