/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computer.laboratory.inventory.system.frames;

import computer.laboratory.inventory.system.Helper;
import computer.laboratory.inventory.system.Tables;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author Tuason
 */
public class InventoryItem extends javax.swing.JFrame {

    private String room;
    private int inventoryId;
    private String date;
    private String inventoryBy;
    
    public InventoryItem(String room, int inventoryId, String date, String inventoryBy) {
        initComponents();
        
        // INITIALIZE VARIABLES
        this.room = room;
        this.inventoryId = inventoryId;
        this.date = date;
        this.inventoryBy = inventoryBy;
        
        // INITIALIZE UI
        dateLabel.setText(date);
        roomLabel.setText(room);
        inventoryOfficer.setText(inventoryBy.toUpperCase());
        
        switch (room) {
            case "Laboratory 1":
                laboratoryIncharge.setText("SYRAEL SOQUE, LPT".toUpperCase());
                break;
            case "Laboratory 2":
                laboratoryIncharge.setText("RICHARD C. CUPAL, LPT".toUpperCase());
                break;
//            default:
//                throw new AssertionError();
        }
        inventoryOfficer.setHorizontalAlignment(SwingConstants.CENTER);
        laboratoryIncharge.setHorizontalAlignment(SwingConstants.CENTER);
        
        // INITIALIZE TABLE
        Tables.getInstance().setInventoryItemTable(inventoryItemTable);
        
        Helper.displayInventoryItems(this.inventoryId, this.room);
        
        // DEFAULT UI
        // UIs
        inventoryItemTable.getTableHeader().setFont(new Font("Leelawadee UI", Font.BOLD, 12));
        inventoryItemTable.getTableHeader().setOpaque(false);
        inventoryItemTable.getTableHeader().setBackground(new Color(255,204,102));
        inventoryItemTable.getTableHeader().setPreferredSize(new Dimension(header.getWidth(), 25));
        
        inventoryItemTable.setDefaultRenderer(Object.class, new AlternateRowColorRenderer());
      
    }
    
    // Custom cell renderer for alternate row colors
    static class AlternateRowColorRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component rendererComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Set alternate row colors
            if (row % 2 == 0) {
                rendererComponent.setBackground(Color.WHITE); // Set the background color for even rows
            } else {
                rendererComponent.setBackground(new Color(240, 240, 240)); // Set the background color for odd rows
            }

            return rendererComponent;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        printBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryItemTable = new javax.swing.JTable();
        creditPanel = new javax.swing.JPanel();
        inventoryOfficer = new javax.swing.JLabel();
        printableText1 = new javax.swing.JLabel();
        laboratoryIncharge = new javax.swing.JLabel();
        printableText3 = new javax.swing.JLabel();
        printableText4 = new javax.swing.JLabel();
        printableText5 = new javax.swing.JLabel();
        printableText6 = new javax.swing.JLabel();
        printableText7 = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(911, 596));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(560, 560));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(560, 560));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(560, 560));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setMaximumSize(new java.awt.Dimension(816, 1056));
        container.setMinimumSize(new java.awt.Dimension(816, 1056));
        container.setPreferredSize(new java.awt.Dimension(816, 1056));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(816, 80));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setText("TALISAY CITY COLLEGE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer/laboratory/inventory/system/images/tcc logo.png"))); // NOI18N
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 70, 70));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer/laboratory/inventory/system/images/back.png"))); // NOI18N
        backBtn.setToolTipText("Back to Home");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        header.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 50));

        container.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(816, 440));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printBtn.setBackground(new java.awt.Color(255, 204, 102));
        printBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printBtn.setText("PRINT");
        printBtn.setToolTipText("Print this page");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        body.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 90, 40));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel1.setText("COMPUTER LABORATORY: ");
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        roomLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        body.add(roomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setText("DATE: ");
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        dateLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        body.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, 30));

        inventoryItemTable.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        inventoryItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Brand Name", "Pieces", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryItemTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventoryItemTable.setFocusable(false);
        inventoryItemTable.setGridColor(new java.awt.Color(0, 0, 0));
        inventoryItemTable.setRowHeight(25);
        inventoryItemTable.setSelectionBackground(new java.awt.Color(255, 204, 102));
        inventoryItemTable.setShowHorizontalLines(true);
        inventoryItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryItemTableMouseClicked(evt);
            }
        });
        inventoryScrollPane.setViewportView(inventoryItemTable);
        if (inventoryItemTable.getColumnModel().getColumnCount() > 0) {
            inventoryItemTable.getColumnModel().getColumn(0).setMinWidth(100);
            inventoryItemTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            inventoryItemTable.getColumnModel().getColumn(0).setMaxWidth(100);
            inventoryItemTable.getColumnModel().getColumn(2).setMinWidth(100);
            inventoryItemTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            inventoryItemTable.getColumnModel().getColumn(2).setMaxWidth(100);
            inventoryItemTable.getColumnModel().getColumn(3).setMinWidth(250);
            inventoryItemTable.getColumnModel().getColumn(3).setPreferredWidth(250);
            inventoryItemTable.getColumnModel().getColumn(3).setMaxWidth(250);
        }

        body.add(inventoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 720, 440));

        creditPanel.setBackground(new java.awt.Color(255, 255, 255));
        creditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryOfficer.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        creditPanel.add(inventoryOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 260, 30));

        printableText1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText1.setText("INVENTORY BY:");
        creditPanel.add(printableText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 30));

        laboratoryIncharge.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        laboratoryIncharge.setText("RICHARD C. CUPAL, LPT");
        creditPanel.add(laboratoryIncharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 30));

        printableText3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText3.setText("Computer Laboratory Officer");
        creditPanel.add(printableText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, 30));

        printableText4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText4.setText("___________________________________________");
        creditPanel.add(printableText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));

        printableText5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText5.setText("Computer Laboratory Officer");
        creditPanel.add(printableText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 30));

        printableText6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText6.setText("NOTED BY:");
        creditPanel.add(printableText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 30));

        printableText7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        printableText7.setText("___________________________________________");
        creditPanel.add(printableText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 30));

        body.add(creditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 900, 320));

        addItemBtn.setBackground(new java.awt.Color(255, 204, 102));
        addItemBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        addItemBtn.setText("Add Item");
        addItemBtn.setToolTipText("Add New Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });
        body.add(addItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 130, 40));

        container.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, 970));

        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // HIDE COMPONENTS
        backBtn.setVisible(false);
        addItemBtn.setVisible(false);
        printBtn.setVisible(false);

        // PRINT
        
        try {
            
            BufferedImage bi = new BufferedImage(container.getWidth(), container.getHeight(), BufferedImage.TYPE_INT_RGB);
            container.paint(bi.getGraphics());
            
            String path = "C:\\Users\\Tuason\\Documents\\printJPG\\inventory-item" + this.date + "-" + this.inventoryId + "-" + this.inventoryBy + ".jpg";
            
            File outputFile = new File(path);
            ImageIO.write(bi, "jpg", outputFile);
            
            // Check if the file exists before attempting to print
            if (outputFile.exists()) {
                Desktop.getDesktop().print(outputFile);
            } else {
                JOptionPane.showMessageDialog(null, "The file doesn't exist: " + path);
            }

        } catch (IOException e) {
            e.printStackTrace(); // Print the stack trace for debugging
            JOptionPane.showMessageDialog(rootPane, "Unable to print. Please try again later.");
        }
        
        // END OF PRINT

        // SHOW COMPONENTS
        backBtn.setVisible(true);
        addItemBtn.setVisible(true);
        printBtn.setVisible(true);
    }//GEN-LAST:event_printBtnActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        new AddNewItem(this.room, this.inventoryId).setVisible(true);    
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new Homepage(this.room).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Homepage(this.room).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void inventoryItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryItemTableMouseClicked
        int index = inventoryItemTable.getSelectedRow();
        TableModel model = inventoryItemTable.getModel();
        int itemId = Integer.parseInt((String) model.getValueAt(index, 0));
        new ItemInformation(itemId, this.inventoryId, this.room).setVisible(true);
    }//GEN-LAST:event_inventoryItemTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new InventoryItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel body;
    private javax.swing.JPanel container;
    private javax.swing.JPanel creditPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel header;
    private javax.swing.JTable inventoryItemTable;
    private javax.swing.JLabel inventoryOfficer;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laboratoryIncharge;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel printableText1;
    private javax.swing.JLabel printableText3;
    private javax.swing.JLabel printableText4;
    private javax.swing.JLabel printableText5;
    private javax.swing.JLabel printableText6;
    private javax.swing.JLabel printableText7;
    private javax.swing.JLabel roomLabel;
    // End of variables declaration//GEN-END:variables
}
